Make changes to the code to fix the following error:

Exception has occurred: TypeError
unhashable type: 'numpy.ndarray'
  File "D:\Repos\gpt-engineer\projects\ddo_buffs\workspace\buff_timer.py", line 8, in update
    self.timers[buff] = time
    ~~~~~~~~~~~^^^^^^
  File "D:\Repos\gpt-engineer\projects\ddo_buffs\workspace\main.py", line 36, in main
    buff_timer.update(buff, time)
  File "D:\Repos\gpt-engineer\projects\ddo_buffs\workspace\main.py", line 48, in <module>
    main()
TypeError: unhashable type: 'numpy.ndarray'
